version: '3.8'

services:
  mongo-user:
    image: mongo
    volumes:
      - ./mongo-data-user:/data/db
    networks:
      - mynetwork

  mongo-product:
    image: mongo
    volumes:
      - ./mongo-data-product:/data/db
    networks:
      - mynetwork

  mongo-order:
    image: mongo
    volumes:
      - ./mongo-data-order:/data/db
    networks:
      - mynetwork

  user-service:
    build:
      context: ./services/userService
    ports:
      - "3001:3001"
    depends_on:
      - mongo-user
    networks:
      - mynetwork

  product-service:
    build:
      context: ./services/productService
    ports:
      - "3002:3002"
    depends_on:
      - mongo-product
    networks:
      - mynetwork

  order-service:
    build:
      context: ./services/orderService
    ports:
      - "3003:3003"
    depends_on:
      - mongo-order
    networks:
      - mynetwork

  # apiGateway:
  #   build:
  #     context: ./services/apiGateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - userService
  #     - productService
  #     - orderService
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: overlay
    attachable: true

